#ifndef SWAN_VERSION_H
#define SWAN_VERSION_H

#define SWAN_VERSION_MAJOR 0
#define SWAN_VERSION_MINOR 5
#define SWAN_VERSION_PATCH 0
#define SWAN_VERSION_STRING "0.5.0"
#define SWAN_MANIFEST_SCHEMA_VERSION 1
#define SWAN_SAVE_FORMAT_VERSION 1

#endif
